### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Souliboi** [seriousm4x/wubbl0rz-archiv-frontend#81]
[Link](https://github.com/seriousm4x/wubbl0rz-archiv-frontend/blob/a7c05b2c3fe9547a973de830f3f7d37da043825b/src/components/Chat.svelte#L124C34-L124C34)
![image](https://github.com/seriousm4x/wubbl0rz-archiv-frontend/assets/106060704/fa3bacce-95ac-415f-8b9f-0c1c8128a0f9)

**Comment by seriousm4x** [comment]
Danke
